### PR TITLE
Change date picker return format

### PR DESCRIPTION
**Pull request by siyu7866**

### CODE REVIEW

**Comment by nash90** [comment]
@siyu7866, Is this issue only on Andriod? In ios and web test I found that the Date is already in format YYYY-MM-DD. Please show the screen shot if there is issue.

**Comment by nash90** [comment]
image

**Comment by siyu7866** [comment]
On Android and chrome, it will return format yyyy/mm/dd

**Comment by siyu7866** [comment]
> @siyu7866, Is this issue only on Andriod? In ios and web test I found that the Date is already in format YYYY-MM-DD. Please show the screen shot if there is issue.

My bad. On chrome, it's correct. I will test that on android again. I am not sure that last is due to date format or network issue.

**Comment by nash90** [comment]
closing this since its not required.

**Pull request closed without merging**
